ALTER TABLE users
ADD COLUMN phone VARCHAR(20),
ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'BYN',
ADD COLUMN email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN transaction_notifications BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN balance_notifications BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE categories
ADD COLUMN budget_limit DECIMAL(19,2),
ADD COLUMN notification_threshold INTEGER DEFAULT 80,
ADD COLUMN is_archived BOOLEAN DEFAULT FALSE,
ADD COLUMN group_name VARCHAR(255),
ADD COLUMN sort_order INTEGER DEFAULT 0;

ALTER TABLE user_settings
ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'BYN',
ADD COLUMN email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN transaction_notifications BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN balance_notifications BOOLEAN NOT NULL DEFAULT TRUE; 