ALTER TABLE categories
ADD COLUMN color VARCHAR(7) NOT NULL DEFAULT '#1e3c72',
ADD COLUMN description TEXT,
ADD COLUMN type VARCHAR(20) NOT NULL DEFAULT 'EXPENSE',
ADD COLUMN user_id BIGINT NOT NULL,
ADD COLUMN transaction_count INT NOT NULL DEFAULT 0,
ADD COLUMN percentage DOUBLE NOT NULL DEFAULT 0.0,
ADD FOREIGN KEY (user_id) REFERENCES users(id); 